module.exports=[
    {
        "courses": [
            {
                "name": "Software Testing Training - Manual & Automation",
                "description": "Comprehensive training covering Manual Testing, Java foundations, Mobile Testing, Automation Testing, Selenium IDE, Selenium WebDriver, Selenium Advanced WebDriver, Selenium Grid, TestNG, SQL Workshop, Performance Testing, JMeter - Advanced, POSTMAN, API Testing, and JIRA.",
                "nextBatch": {
                    "Cochin": "July 17th, 2024 (Offline & Online)",
                    "Calicut": "July 17th, 2024 (Offline Only)"
                },
                "duration": "4 Months, 5 Days a Week, 1.5 - 2 Hours/day",
                "fee": {
                    "EMI Mode": "41,000 INR",
                    "One-time Payment Mode": "37,500 INR"
                }
            },
            {
                "name": "Python Data Science - ML - AI - & Power BI",
                "description": "Training on Introduction to AWS, Amazon IAM, Elastic Computing (EC2), and Simple Storage Service (S3), with a focus on machine learning and data science.",
                "nextBatch": {
                    "Cochin": "August 12th, 2024 (Offline & Online)",
                    "Calicut": "September 18th, 2024 (Offline)"
                },
                "duration": "7 Months, 5 Days a Week, 1.5 - 2 Hours/day",
                "fee": {
                    "EMI Mode": "72,000 INR",
                    "One-time Payment Mode": "64,500 INR"
                }
            },
            {
                "name": "MEA(R)N Stack Web Development Expert - Angular & React",
                "description": "Covers HTML, CSS, Bootstrap, JavaScript, TypeScript, Git, Angular, React.js, Node.js, Express.js, and MongoDB.",
                "nextBatch": {
                    "Cochin": "August 12th, 2024 (Offline & Online)",
                    "Calicut": "July 19th, 2024 (Offline)"
                },
                "duration": "6 Months, 5 Days a Week, 1.5 - 2 Hours/day",
                "fee": {
                    "EMI Mode": "55,000 INR",
                    "One-time Payment Mode": "49,500 INR"
                }
            },
            {
                "name": "Python Django - React - Full Stack Web Development Expert",
                "description": "Training includes Core Python, Basics of Programming, Unix Commands, Advanced Python, Django Framework, REST API, Git, ReactJS, Web Concepts & Tools.",
                "nextBatch": {
                    "Cochin": "July 17th, 2024 (Offline & Online)",
                    "Calicut": "July 17th, 2024 (Offline Only)"
                },
                "duration": "6.5 Months, 5 Days a Week, 2 Hours/day",
                "fee": {
                    "EMI Mode": "45,000 INR",
                    "One-time Payment Mode": "39,500 INR"
                }
            },
            {
                "name": "Asp.net MVC with Angular - Full Stack",
                "description": "Training on Git installation, repository creation in GitHub, Git commands, and real-time code integration.",
                "nextBatch": {
                    "Cochin": "July 17th, 2024 (Offline & Online)",
                    "Calicut": "Not Available"
                },
                "duration": "5 Months, 5 Days a Week, 2 Hours/day",
                "fee": {
                    "EMI Mode": "45,000 INR",
                    "One-time Payment Mode": "39,500 INR"
                }
            },
            {
                "name": "Best Flutter Training",
                "description": "Comprehensive training on Dart, Flutter, Android Studio, UI Designing, Firebase, API Testing, and more.",
                "nextBatch": {
                    "Cochin": "July 17th, 2024 (Offline & Online)",
                    "Calicut": "July 17th, 2024 (Offline Only)"
                },
                "duration": "5 Months, 2 Hours/day",
                "fee": {
                    "EMI Mode": "41,000 INR",
                    "One-time Payment Mode": "37,500 INR"
                }
            },
            {
                "name": "Java Spring Full Stack Development",
                "description": "Training includes Java Fundamentals, OOPS, Advanced Java, Java Database Programming, JDK New Features, Java EE, JPA & Hibernate, Spring & Spring Boot.",
                "nextBatch": {
                    "Cochin": "August 21st, 2024 (09:00 AM - 11:00 AM)",
                    "Calicut": "Not Available"
                },
                "duration": "4 Months, 5 Days a Week, 2 Hours/day",
                "fee": {
                    "EMI Mode": "41,000 INR",
                    "One-time Payment Mode": "37,500 INR"
                }
            }
        ]
    }
    
    // {"key": "hello", "value": "Hello! How can I assist you today?"},
    // {"key": "hi", "value": "Hi there! How can I help you?"},
    // {"key": "good morning", "value": "Good morning! How can I assist you today?"},
    // {"key": "good afternoon", "value": "Good afternoon! How can I help you?"},
    // {"key": "good evening", "value": "Good evening! How can I assist you?"},
    // {"key": "course details for software testing", "value": "The Software Testing course includes Manual Testing, Java foundations, Mobile Testing, and Automation Testing including Selenium."},
    // {"key": "course details for machine learning", "value": "The Python Data Science - ML - AI & Power BI course includes AWS, IAM, EC2, S3, and more."},
    // {"key": "course details for mean stack", "value": "The MEAN Stack Web Development Expert course includes HTML, CSS, JavaScript, Angular, React.js, Node.js, Express.js, and MongoDB."},
    // {"key": "course details for python django", "value": "The Python Django - React Full Stack Web Development Expert course includes Core Python, Django Framework, REST API, and ReactJs."},
    // {"key": "course details for asp.net mvc", "value": "The Asp.net MVC with Angular Full Stack course includes Git, real-time code integration, and more."},
    // {"key": "course details for flutter", "value": "The Flutter Training includes Dart, Flutter, Android Studio, and various mobile app development techniques."},
    // {"key": "course details for java spring", "value": "The Java Spring Full Stack Development course includes Java Fundamentals, Advanced Java, Spring & Spring Boot."},
    // {"key": "next batch for software testing in cochin", "value": "The next batch for Software Testing in Cochin starts on July 17th, 2024 (Offline & Online)."},
    // {"key": "next batch for software testing in calicut", "value": "The next batch for Software Testing in Calicut starts on July 17th, 2024 (Offline Only)."},
    // {"key": "next batch for python data science in cochin", "value": "The next batch for Python Data Science in Cochin starts on August 12th, 2024 (Offline & Online)."},
    // {"key": "next batch for python data science in calicut", "value": "The next batch for Python Data Science in Calicut starts on September 18th, 2024 (Offline Only)."},
    // {"key": "next batch for mean stack in cochin", "value": "The next batch for MEAN Stack Web Development in Cochin starts on August 12th, 2024 (Offline & Online)."},
    // {"key": "next batch for mean stack in calicut", "value": "The next batch for MEAN Stack Web Development in Calicut starts on July 19th, 2024 (Offline Only)."},
    // {"key": "next batch for python django in cochin", "value": "The next batch for Python Django - React Full Stack in Cochin starts on July 17th, 2024 (Offline & Online)."},
    // {"key": "next batch for python django in calicut", "value": "The next batch for Python Django - React Full Stack in Calicut starts on July 17th, 2024 (Offline Only)."},
    // {"key": "next batch for asp.net mvc in cochin", "value": "The next batch for Asp.net MVC with Angular Full Stack in Cochin starts on July 17th, 2024 (Offline & Online)."},
    // {"key": "next batch for asp.net mvc in calicut", "value": "Asp.net MVC with Angular Full Stack is not available in Calicut."},
    // {"key": "next batch for flutter in cochin", "value": "The next batch for Flutter Training in Cochin starts on July 17th, 2024 (Offline & Online)."},
    // {"key": "next batch for flutter in calicut", "value": "The next batch for Flutter Training in Calicut starts on July 17th, 2024 (Offline Only)."},
    // {"key": "next batch for java spring in cochin", "value": "The next batch for Java Spring Full Stack Development in Cochin starts on August 21st, 2024 (09:00 AM - 11:00 AM)."},
    // {"key": "next batch for java spring in calicut", "value": "Java Spring Full Stack Development is not available in Calicut."},
    // {"key": "duration for software testing", "value": "The Software Testing course duration is 4 months, 5 days a week, 1.5 - 2 hours per day."},
    // {"key": "duration for python data science", "value": "The Python Data Science course duration is 7 months, 5 days a week, 1.5 - 2 hours per day."},
    // {"key": "duration for mean stack", "value": "The MEAN Stack Web Development course duration is 6 months, 5 days a week, 1.5 - 2 hours per day."},
    // {"key": "duration for python django", "value": "The Python Django - React Full Stack course duration is 6.5 months, 5 days a week, 2 hours per day."},
    // {"key": "duration for asp.net mvc", "value": "The Asp.net MVC with Angular Full Stack course duration is 5 months, 5 days a week, 2 hours per day."},
    // {"key": "duration for flutter", "value": "The Flutter Training duration is 5 months, 2 hours per day."},
    // {"key": "duration for java spring", "value": "The Java Spring Full Stack Development course duration is 4 months, 5 days a week, 2 hours per day."},
    // {"key": "fees for software testing emi", "value": "The EMI mode fee for Software Testing is 41,000 INR."},
    // {"key": "fees for software testing one time", "value": "The one-time payment mode fee for Software Testing is 37,500 INR."},
    // {"key": "fees for python data science emi", "value": "The EMI mode fee for Python Data Science is 72,000 INR."},
    // {"key": "fees for python data science one time", "value": "The one-time payment mode fee for Python Data Science is 64,500 INR."},
    // {"key": "fees for mean stack emi", "value": "The EMI mode fee for MEAN Stack Web Development is 55,000 INR."},
    // {"key": "fees for mean stack one time", "value": "The one-time payment mode fee for MEAN Stack Web Development is 49,500 INR."},
    // {"key": "fees for python django emi", "value": "The EMI mode fee for Python Django - React Full Stack is 45,000 INR."},
    // {"key": "fees for python django one time", "value": "The one-time payment mode fee for Python Django - React Full Stack is 39,500 INR."},
    // {"key": "fees for asp.net mvc emi", "value": "The EMI mode fee for Asp.net MVC with Angular Full Stack is 45,000 INR."},
    // {"key": "fees for asp.net mvc one time", "value": "The one-time payment mode fee for Asp.net MVC with Angular Full Stack is 39,500 INR."},
    // {"key": "fees for flutter emi", "value": "The EMI mode fee for Flutter Training is 41,000 INR."},
    // {"key": "fees for flutter one time", "value": "The one-time payment mode fee for Flutter Training is 37,500 INR."},
    // {"key": "fees for java spring emi", "value": "The EMI mode fee for Java Spring Full Stack Development is 41,000 INR."},
    // {"key": "fees for java spring one time", "value": "The one-time payment mode fee for Java Spring Full Stack Development is 37,500 INR."},
    // {"key": "software testing prerequisites", "value": "No specific prerequisites are required for the Software Testing course."},
    // {"key": "python data science prerequisites", "value": "Basic understanding of Python programming is recommended for the Python Data Science course."},
    // {"key": "mean stack prerequisites", "value": "Basic knowledge of HTML, CSS, and JavaScript is recommended for the MEAN Stack Web Development course."},
    // {"key": "python django prerequisites", "value": "Basic understanding of Python programming is recommended for the Python Django course."},
    // {"key": "asp.net mvc prerequisites", "value": "Basic knowledge of C# and .NET is recommended for the Asp.net MVC course."},
    // {"key": "flutter prerequisites", "value": "Basic knowledge of Dart programming is recommended for the Flutter Training."},
    // {"key": "java spring prerequisites", "value": "Basic understanding of Java programming is recommended for the Java Spring Full Stack Development course."},
    // {"key": "software testing job placement", "value": "Job placement assistance is provided for the Software Testing course."},
    // {"key": "python data science job placement", "value": "Job placement assistance is provided for the Python Data Science course."},
    // {"key": "mean stack job placement", "value": "Job placement assistance is provided for the MEAN Stack Web Development course."},
    // {"key": "python django job placement", "value": "Job placement assistance is provided for the Python Django - React Full Stack course."},
    // {"key": "asp.net mvc job placement", "value": "Job placement assistance is provided for the Asp.net MVC with Angular Full Stack course."},
    // {"key": "flutter job placement", "value": "Job placement assistance is provided for the Flutter Training."},
    // {"key": "java spring job placement", "value": "Job placement assistance is provided for the Java Spring Full Stack Development course."},
    // {"key": "software testing course material", "value": "Course materials for Software Testing include textbooks, online resources, and practical exercises."},
    // {"key": "python data science course material", "value": "Course materials for Python Data Science include textbooks, online resources, and hands-on projects."},
    // {"key": "mean stack course material", "value": "Course materials for MEAN Stack Web Development include textbooks, online resources, and coding assignments."},
    // {"key": "python django course material", "value": "Course materials for Python Django include textbooks, online resources, and practical projects."},
    // {"key": "asp.net mvc course material", "value": "Course materials for Asp.net MVC with Angular include textbooks, online resources, and coding exercises."},
    // {"key": "flutter course material", "value": "Course materials for Flutter Training include textbooks, online resources, and app development projects."},
    // {"key": "java spring course material", "value": "Course materials for Java Spring Full Stack Development include textbooks, online resources, and coding tasks."},
    // {"key": "software testing certification", "value": "Certification is provided upon successful completion of the Software Testing course."},
    // {"key": "python data science certification", "value": "Certification is provided upon successful completion of the Python Data Science course."},
    // {"key": "mean stack certification", "value": "Certification is provided upon successful completion of the MEAN Stack Web Development course."},
    // {"key": "python django certification", "value": "Certification is provided upon successful completion of the Python Django - React Full Stack course."},
    // {"key": "asp.net mvc certification", "value": "Certification is provided upon successful completion of the Asp.net MVC with Angular Full Stack course."},
    // {"key": "flutter certification", "value": "Certification is provided upon successful completion of the Flutter Training."},
    // {"key": "java spring certification", "value": "Certification is provided upon successful completion of the Java Spring Full Stack Development course."},
    // {"key": "software testing class timing", "value": "Classes for Software Testing are held 5 days a week, 1.5 - 2 hours per day."},
    // {"key": "python data science class timing", "value": "Classes for Python Data Science are held 5 days a week, 1.5 - 2 hours per day."},
    // {"key": "mean stack class timing", "value": "Classes for MEAN Stack Web Development are held 5 days a week, 1.5 - 2 hours per day."},
    // {"key": "python django class timing", "value": "Classes for Python Django - React Full Stack are held 5 days a week, 2 hours per day."},
    // {"key": "asp.net mvc class timing", "value": "Classes for Asp.net MVC with Angular Full Stack are held 5 days a week, 2 hours per day."},
    // {"key": "flutter class timing", "value": "Classes for Flutter Training are held 2 hours per day."},
    // {"key": "java spring class timing", "value": "Classes for Java Spring Full Stack Development are held 5 days a week, 2 hours per day."},
    // {"key": "software testing online classes", "value": "Yes, Software Testing classes are available online."},
    // {"key": "python data science online classes", "value": "Yes, Python Data Science classes are available online."},
    // {"key": "mean stack online classes", "value": "Yes, MEAN Stack Web Development classes are available online."},
    // {"key": "python django online classes", "value": "Yes, Python Django - React Full Stack classes are available online."},
    // {"key": "asp.net mvc online classes", "value": "Yes, Asp.net MVC with Angular Full Stack classes are available online."},
    // {"key": "flutter online classes", "value": "Yes, Flutter Training classes are available online."},
    // {"key": "java spring online classes", "value": "Yes, Java Spring Full Stack Development classes are available online."},
    // {"key": "software testing offline classes", "value": "Yes, Software Testing classes are available offline in Cochin and Calicut."},
    // {"key": "python data science offline classes", "value": "Yes, Python Data Science classes are available offline in Cochin and Calicut."},
    // {"key": "mean stack offline classes", "value": "Yes, MEAN Stack Web Development classes are available offline in Cochin and Calicut."},
    // {"key": "python django offline classes", "value": "Yes, Python Django - React Full Stack classes are available offline in Cochin and Calicut."},
    // {"key": "asp.net mvc offline classes", "value": "Yes, Asp.net MVC with Angular Full Stack classes are available offline in Cochin."},
    // {"key": "flutter offline classes", "value": "Yes, Flutter Training classes are available offline in Cochin and Calicut."},
    // {"key": "java spring offline classes", "value": "Yes, Java Spring Full Stack Development classes are available offline in Cochin."},
    // {"key": "contact for more information", "value": "For more information, please contact our support team at support@example.com or call us at +1234567890."},
    // {"key": "software testing enrollment", "value": "To enroll in the Software Testing course, visit our website and fill out the registration form."},
    // {"key": "python data science enrollment", "value": "To enroll in the Python Data Science course, visit our website and fill out the registration form."},
    // {"key": "mean stack enrollment", "value": "To enroll in the MEAN Stack Web Development course, visit our website and fill out the registration form."},
    // {"key": "python django enrollment", "value": "To enroll in the Python Django - React Full Stack course, visit our website and fill out the registration form."},
    // {"key": "asp.net mvc enrollment", "value": "To enroll in the Asp.net MVC with Angular Full Stack course, visit our website and fill out the registration form."},
    // {"key": "flutter enrollment", "value": "To enroll in the Flutter Training, visit our website and fill out the registration form."},
    // {"key": "java spring enrollment", "value": "To enroll in the Java Spring Full Stack Development course, visit our website and fill out the registration form."},
    // {"key": "software testing course requirements", "value": "No specific requirements are needed for the Software Testing course."},
    // {"key": "python data science course requirements", "value": "Basic Python programming knowledge is required for the Python Data Science course."},
    // {"key": "mean stack course requirements", "value": "Basic knowledge of HTML, CSS, and JavaScript is required for the MEAN Stack Web Development course."},
    // {"key": "python django course requirements", "value": "Basic knowledge of Python is required for the Python Django course."},
    // {"key": "asp.net mvc course requirements", "value": "Basic knowledge of C# and .NET is required for the Asp.net MVC course."},
    // {"key": "flutter course requirements", "value": "Basic knowledge of Dart programming is required for the Flutter Training."},
    // {"key": "java spring course requirements", "value": "Basic knowledge of Java is required for the Java Spring Full Stack Development course."},
    // {"key": "software testing job assistance", "value": "We provide job assistance and support to help you find a suitable job after completing the Software Testing course."},
    // {"key": "python data science job assistance", "value": "We offer job assistance and career support for graduates of the Python Data Science course."},
    // {"key": "mean stack job assistance", "value": "Job assistance and career support are provided for graduates of the MEAN Stack Web Development course."},
    // {"key": "python django job assistance", "value": "We offer job assistance and career support for graduates of the Python Django - React Full Stack course."},
    // {"key": "asp.net mvc job assistance", "value": "Job assistance and career support are available for graduates of the Asp.net MVC with Angular Full Stack course."},
    // {"key": "flutter job assistance", "value": "We provide job assistance and career support for graduates of the Flutter Training."},
    // {"key": "java spring job assistance", "value": "Job assistance and career support are provided for graduates of the Java Spring Full Stack Development course."},
    // {"key": "software testing course feedback", "value": "You can provide feedback about the Software Testing course on our website or through our feedback form."},
    // {"key": "python data science course feedback", "value": "Feedback for the Python Data Science course can be submitted on our website or through our feedback form."},
    // {"key": "mean stack course feedback", "value": "Submit your feedback for the MEAN Stack Web Development course on our website or through our feedback form."},
    // {"key": "python django course feedback", "value": "Provide feedback for the Python Django - React Full Stack course on our website or through our feedback form."},
    // {"key": "asp.net mvc course feedback", "value": "Feedback for the Asp.net MVC with Angular Full Stack course can be provided on our website or through our feedback form."},
    // {"key": "flutter course feedback", "value": "Submit your feedback for the Flutter Training on our website or through our feedback form."},
    // {"key": "java spring course feedback", "value": "Feedback for the Java Spring Full Stack Development course can be provided on our website or through our feedback form."},
    // {"key": "what is manual testing", "value": "Manual testing involves manually checking software for defects without using automation tools. It requires testers to perform test cases and report bugs."},
    // {"key": "what is selenium", "value": "Selenium is a suite of tools for automated testing of web applications. It supports various programming languages and browsers."},
    // {"key": "what is API testing", "value": "API testing involves checking the functionality, reliability, and security of APIs. It ensures that the APIs work as expected and handle errors properly."},
    // {"key": "what is JMeter", "value": "JMeter is an open-source tool for performance testing. It helps in testing the load and performance of web applications and services."},
    // {"key": "what is TestNG", "value": "TestNG is a testing framework inspired by JUnit and NUnit. It is used for running automated tests and supports various test configurations."},
    // {"key": "what is SQL workshop", "value": "SQL Workshop involves learning SQL (Structured Query Language) for managing and querying databases effectively."},
    // {"key": "what is JIRA", "value": "JIRA is a project management tool used for tracking issues, bugs, and project progress. It is widely used in software development teams."},
    // {"key": "what is Docker", "value": "Docker is a platform for developing, shipping, and running applications inside lightweight, portable containers."},
    // {"key": "what is AWS", "value": "Amazon Web Services (AWS) is a cloud computing platform offering a wide range of services, including computing power, storage, and databases."},
    // {"key": "what is IAM in AWS", "value": "IAM (Identity and Access Management) in AWS allows you to manage user permissions and access to AWS services and resources."},
    // {"key": "what is EC2", "value": "EC2 (Elastic Compute Cloud) is an AWS service that provides scalable virtual servers for running applications and services."},
    // {"key": "what is S3", "value": "S3 (Simple Storage Service) is an AWS service for storing and retrieving any amount of data at any time, from anywhere on the web."},
    // {"key": "what is React", "value": "React is a JavaScript library for building user interfaces, developed by Facebook. It allows for the creation of single-page applications with a component-based architecture."},
    // {"key": "what is Angular", "value": "Angular is a web application framework developed by Google. It is used for building dynamic, single-page applications with a rich user experience."},
    // {"key": "what is Node.js", "value": "Node.js is a JavaScript runtime built on Chrome's V8 engine that allows you to build scalable network applications. It is widely used for server-side development."},
    // {"key": "what is Express.js", "value": "Express.js is a web application framework for Node.js that simplifies the process of building server-side applications and APIs."},
    // {"key": "what is MongoDB", "value": "MongoDB is a NoSQL database that stores data in JSON-like documents, providing high performance and flexibility for managing large amounts of unstructured data."},
    // {"key": "what is Django", "value": "Django is a high-level Python web framework that allows developers to create robust, scalable web applications quickly and efficiently."},
    // {"key": "what is REST API", "value": "A REST API (Representational State Transfer API) is an interface for interacting with web services using standard HTTP methods like GET, POST, PUT, and DELETE."},
    // {"key": "what is Flutter", "value": "Flutter is an open-source UI software development toolkit by Google for building natively compiled applications for mobile, web, and desktop from a single codebase."},
    // {"key": "what is Dart", "value": "Dart is a programming language developed by Google, optimized for building mobile, desktop, and web applications with the Flutter framework."},
    // {"key": "what is Spring Boot", "value": "Spring Boot is an extension of the Spring framework that simplifies the setup and development of production-ready Spring applications."},
    // {"key": "how can I enroll in a course", "value": "To enroll in a course, visit our website, select the course you're interested in, and complete the registration form."},
    // {"key": "what is the course fee for software testing", "value": "The fee for the Software Testing course is 41,000 INR for EMI mode and 37,500 INR for one-time payment mode."},
    // {"key": "is there any discount on course fees", "value": "Currently, we offer discounts for one-time payments. Please contact our support team for more details on any available offers."},
    // {"key": "can I pay course fees in installments", "value": "Yes, we offer EMI options for paying course fees. Please select the EMI option during registration."},
    // {"key": "what is the duration of the flutter course", "value": "The Flutter course duration is 5 months, with classes held for 2 hours per day."},
    // {"key": "what is covered in the Java Spring course", "value": "The Java Spring course covers Java Fundamentals, OOPS, Advanced Java, Java EE, JPA & Hibernate, and Spring Boot."},
    // {"key": "where can I view course materials", "value": "Course materials are available on our learning platform. You can access them once you're enrolled in the course."},
    // {"key": "is job placement assistance provided", "value": "Yes, we provide job placement assistance for all our courses to help you find suitable employment after graduation."},
    // {"key": "what are the prerequisites for the mean stack course", "value": "Basic knowledge of HTML, CSS, and JavaScript is recommended for the MEAN Stack Web Development course."},
    // {"key": "can I attend classes online", "value": "Yes, we offer both offline and online classes for most of our courses. You can choose the mode of learning during registration."},
    // {"key": "how do I contact support", "value": "You can contact our support team via email at support@example.com or call us at +1234567890."},
    // {"key": "how do I reset my password", "value": "To reset your password, go to the login page, click on 'Forgot Password,' and follow the instructions to reset it."},
    // {"key": "how can I provide feedback on the course", "value": "You can provide feedback through our website's feedback form or by contacting our support team."},
    // {"key": "are there any prerequisites for the python django course", "value": "Basic knowledge of Python programming is required for the Python Django course."},
    // {"key": "what is covered in the software testing course", "value": "The Software Testing course covers Manual Testing, Java foundations, Mobile Testing, Automation Testing, and more."},
    // {"key": "what is included in the flutter training", "value": "The Flutter Training includes Dart, Flutter framework, Android Studio, UI designing, and app development projects."},
    // {"key": "when does the next batch start", "value": "The start dates for the next batches are listed on our website. Please check the specific course page for details."},
    // {"key": "where are the offline classes held", "value": "Offline classes are held at our centers in Cochin and Calicut. Please check the course details for the exact location."},
    // {"key": "how long is the mean stack course", "value": "The MEAN Stack Web Development course lasts for 6 months, with classes held 5 days a week."},
    // {"key": "what is the format of online classes", "value": "Online classes are conducted via live video sessions, with recorded sessions and interactive exercises available on our platform."},
    // {"key": "what is the fee for the Java Spring course", "value": "The fee for the Java Spring Full Stack Development course is 41,000 INR for EMI mode and 37,500 INR for one-time payment mode."},
    // {"key": "is there a refund policy", "value": "Yes, we have a refund policy. Please refer to our terms and conditions on the website for more details."},
    // {"key": "can I change my course after enrollment", "value": "Yes, you can request a change in course after enrollment. Please contact our support team to discuss your options."},
    // {"key": "how do I get the course certificate", "value": "You will receive a course certificate upon successful completion of the course. It will be issued after final assessments and project work."},
    // {"key": "what tools are used in the software testing course", "value": "The Software Testing course includes tools like Selenium, JMeter, POSTMAN, and JIRA."},
    // {"key": "what is included in the Python Data Science course", "value": "The Python Data Science course includes AWS, IAM, EC2, S3, and various data science and machine learning techniques."},
    // {"key": "are there any group discounts available", "value": "Yes, we offer group discounts for corporate training or group enrollments. Please contact us for more information."},
    // {"key": "can I switch between online and offline classes", "value": "Yes, you can request to switch between online and offline classes. Please check with our support team for availability and procedures."},
    // {"key": "do you offer career counseling", "value": "Yes, we offer career counseling services to help you plan your career path and find suitable job opportunities."},
    // {"key": "what is the focus of the Asp.net MVC course", "value": "The Asp.net MVC course focuses on web application development using ASP.NET MVC framework, including Git integration and repository management."},
    // {"key": "how do I access course recordings", "value": "Course recordings are available on our learning platform. You can access them through your course dashboard."},
    // {"key": "is there a trial class available", "value": "Yes, we offer trial classes for most of our courses. Please contact our support team to schedule a trial session."},
    // {"key": "what are the payment options for course fees", "value": "We accept various payment options including credit/debit cards, bank transfers, and EMI payments."},
    // {"key": "how can I get a course syllabus", "value": "The course syllabus is available on our website. You can also request it from our support team if you need more details."},
    // {"key": "what is the refund policy for course cancellations", "value": "Refund policies for course cancellations are detailed on our website. Please refer to the terms and conditions for more information."},
    // {"key": "are there any prerequisites for the Java Spring course", "value": "Basic knowledge of Java programming is required for the Java Spring Full Stack Development course."},
    // {"key": "what is the mode of delivery for offline classes", "value": "Offline classes are conducted in-person at our training centers with hands-on practice and instructor-led sessions."},
    // {"key": "can I get a demo before enrolling", "value": "Yes, you can request a demo class to get an overview of the course content and teaching methodology."},
    // {"key": "how do I contact the instructor", "value": "You can contact the instructor through the learning platform or by emailing support@example.com for further assistance."},
    // {"key": "what is the course fee for mean stack", "value": "The fee for the MEAN Stack Web Development course is 55,000 INR for EMI mode and 49,500 INR for one-time payment mode."},
    // {"key": "is there any job guarantee", "value": "We offer job placement assistance but do not guarantee job placement. We provide support to help you find job opportunities."},
    // {"key": "what are the benefits of the Flutter course", "value": "The Flutter course equips you with skills to develop cross-platform mobile applications with a single codebase, using the Dart language and Flutter framework."},
    // {"key": "what does the Python Django course cover", "value": "The Python Django course covers core Python programming, Django framework, REST API development, and full-stack web development with React."},
    // {"key": "is there any internship opportunity", "value": "Some courses may offer internship opportunities or project work. Please check with the course details or contact our support team."},
    // {"key": "how do I check my course progress", "value": "You can track your course progress through the learning platform, where you will find assignments, quizzes, and completion status."},
    // {"key": "what is the course format for software testing", "value": "The Software Testing course includes theoretical lessons, practical exercises, and real-world projects to provide comprehensive training."},
    // {"key": "what kind of projects are included in the flutter course", "value": "The Flutter course includes building practical projects such as mobile apps with various functionalities and UI designs."},
    // {"key": "how can I request a course extension", "value": "To request a course extension, please contact our support team with your request and reasons for the extension."},
    // {"key": "can I receive a course certificate if I miss some classes", "value": "Certification is awarded upon successful completion of the course requirements, including attendance, assignments, and projects."},
    // {"key": "are there any live sessions in the courses", "value": "Yes, our courses include live sessions where instructors teach and interact with students in real-time."},
    // {"key": "how can I get a copy of the course materials", "value": "Course materials are provided through the learning platform. You can download them as needed once enrolled in the course."},
    // {"key": "what is the focus of the Python Data Science course", "value": "The Python Data Science course focuses on data analysis, machine learning, and data visualization using Python and various data science tools."},
    // {"key": "are there any additional costs for course materials", "value": "All necessary course materials are included in the course fee. There are no additional costs for accessing course resources."},
    // {"key": "what is the format of the online classes", "value": "Online classes include live video sessions, recorded lectures, and interactive exercises accessible through our learning platform."},
    // {"key": "can I get a refund if I change my mind", "value": "Refund policies are outlined on our website. Please review the terms and conditions or contact support for more information on refunds."},
    // {"key": "is there a course completion project", "value": "Yes, most of our courses include a final project to apply the skills learned throughout the course and demonstrate your proficiency."},
    // {"key": "how do I update my contact information", "value": "To update your contact information, log in to your account on our website and update your profile details or contact support for assistance."},
    // {"key": "what support is available for students", "value": "We offer various support services including technical assistance, career counseling, and access to a dedicated help desk for course-related queries."},
    // {"key": "are there any networking opportunities", "value": "Yes, we provide networking opportunities through workshops, webinars, and events where students can connect with industry professionals and peers."},
    // {"key": "how do I access live class recordings", "value": "Live class recordings are available on the learning platform under your course dashboard for on-demand viewing."},
    // {"key": "what are the eligibility criteria for the Java Spring course", "value": "Basic understanding of Java programming and web development concepts is recommended for the Java Spring Full Stack Development course."},
    // {"key": "can I attend multiple courses simultaneously", "value": "Yes, you can enroll in multiple courses. Please ensure you can manage the schedules and workloads effectively."},
    // {"key": "how can I get technical support", "value": "Technical support is available through our help desk on the learning platform or by contacting support@example.com."},
    // {"key": "is there a mobile app for accessing course materials", "value": "Currently, we provide access to course materials through our website. There is no dedicated mobile app at this time."},
    // {"key": "how can I apply for a scholarship", "value": "Scholarship applications are accepted through our website. Please check the scholarship section for eligibility criteria and application procedures."},
    // {"key": "what is the teaching methodology for the courses", "value": "Our teaching methodology includes a mix of theoretical lessons, practical exercises, live sessions, and hands-on projects to ensure comprehensive learning."},
    // {"key": "how often are new batches started", "value": "New batches are started periodically. Check the specific course page on our website for upcoming batch dates and availability."},
    // {"key": "can I transfer to a different batch", "value": "Yes, you can request a transfer to a different batch. Please contact our support team to check for availability and transfer procedures."},
    // {"key": "are there any group study options", "value": "We offer group study options and collaborative projects. You can connect with fellow students through the course platform."},
    // {"key": "how can I get in touch with my course peers", "value": "You can connect with your course peers through discussion forums, group projects, and networking events organized by us."},
    // {"key": "is there any after-course support available", "value": "Yes, we offer post-course support including career guidance, job placement assistance, and continued access to learning resources."},
    // {"key": "how can I track my course progress", "value": "Track your course progress through the learning platform, where you can see completed modules, assignments, and overall progress."},
    // {"key": "what is the duration of the Python Data Science course", "value": "The Python Data Science course lasts for 7 months, with classes held 5 days a week, 1.5 - 2 hours per day."},
    // {"key": "can I get a refund if I’m not satisfied", "value": "Refunds are available according to our refund policy. Please review the terms on our website or contact support for more information."},
    // {"key": "what are the technical requirements for online classes", "value": "Technical requirements include a stable internet connection, a computer or tablet, and access to video conferencing tools like Zoom."},
    // {"key": "how can I get a demo of the learning platform", "value": "To get a demo of the learning platform, contact our support team to schedule a walkthrough or trial access."},
    // {"key": "what are the benefits of the Asp.net MVC course", "value": "The Asp.net MVC course provides skills in developing web applications with ASP.NET MVC, including real-time code integration and Git usage."},
    // {"key": "how do I access course assignments", "value": "Course assignments are available on the learning platform under your course dashboard. You can download and submit assignments online."},
    // {"key": "is there a live Q&A session", "value": "Yes, we organize live Q&A sessions with instructors to address any questions or concerns you may have during the course."},
    // {"key": "how do I update my enrollment details", "value": "To update your enrollment details, log in to your account on our website and modify your profile or contact support for assistance."},
    // {"key": "what is covered in the Python Django course", "value": "The Python Django course covers core Python programming, Django framework, REST API development, and React for full-stack development."},
    // {"key": "can I request additional support materials", "value": "Additional support materials can be requested from the course instructor or through the learning platform's support section."},
    // {"key": "how do I participate in group projects", "value": "Group projects are part of the course curriculum. You will be assigned to groups and can collaborate with peers through the course platform."},
    // {"key": "what is the format of course assessments", "value": "Course assessments include quizzes, assignments, and projects to evaluate your understanding and practical skills."},
    // {"key": "how can I get in touch with the course coordinator", "value": "You can contact the course coordinator through the learning platform or by emailing support@example.com for any course-related queries."},
    // {"key": "what are the key topics in the MEAN stack course", "value": "The MEAN Stack course covers HTML, CSS, Bootstrap, JavaScript, Angular, React.js, Node.js, Express.js, and MongoDB."},
    // {"key": "what is the course schedule", "value": "Course schedules are available on the course page on our website. It includes details on class timings and session frequency."},
    // {"key": "can I access the course materials offline", "value": "Course materials are primarily available online. Some resources may be downloadable for offline access."},
    // {"key": "how can I get a course completion certificate", "value": "A course completion certificate is awarded upon fulfilling all course requirements, including attendance, assignments, and projects."},
    // {"key": "what kind of projects are included in the Django course", "value": "The Django course includes projects such as developing web applications, RESTful APIs, and integrating with React for full-stack development."},
    // {"key": "what are the benefits of taking the Java Spring course", "value": "The Java Spring course provides comprehensive knowledge in Java programming, Spring framework, and building enterprise-level applications."},
    // {"key": "how can I get support for technical issues", "value": "For technical support, you can contact our help desk via the learning platform or email support@example.com."},
    // {"key": "what is the structure of the online classes", "value": "Online classes include live lectures, interactive sessions, recorded videos, and hands-on exercises accessible through the course platform."},
    // {"key": "can I get a refund if I withdraw from the course", "value": "Refunds for withdrawal are subject to our refund policy. Please refer to our terms and conditions or contact support for details."},
    // {"key": "how do I apply for a course", "value": "To apply for a course, visit our website, select the desired course, and complete the registration form."},
    // {"key": "what is covered in the software testing course", "value": "The Software Testing course includes manual testing, automation testing, Java foundations, Selenium, JMeter, and API testing."},
    // {"key": "how can I contact other students", "value": "You can contact other students through the discussion forums, group projects, and networking events organized by us."},
    // {"key": "what is the duration of the Java Spring course", "value": "The Java Spring Full Stack Development course is 4 months long, with classes held 5 days a week for 2 hours per day."},
    // {"key": "how do I access course feedback forms", "value": "Feedback forms are available on our website or through the learning platform once you are enrolled in a course."},
    // {"key": "what is included in the full-stack web development course", "value": "The Full Stack Web Development course includes front-end technologies like HTML, CSS, JavaScript, and back-end technologies like Node.js, Express.js, and MongoDB."},
    // {"key": "can I switch between offline and online classes", "value": "Yes, you can request to switch between offline and online classes. Please contact our support team for more information."},
    // {"key": "how do I receive my course certificate", "value": "Your course certificate will be sent to your registered email address or made available for download on the learning platform upon course completion."},
    // {"key": "what is the course fee for manual testing?", "value": "The course fee for Manual Testing is 41,000 INR for EMI mode and 37,500 INR for one-time payment mode."},
    // {"key": "when does the next batch for Python Data Science start?", "value": "The next batch for Python Data Science starts on August 12th, 2024, in Cochin and September 18th, 2024, in Calicut."},
    // {"key": "is the MEAN stack course online?", "value": "Yes, the MEAN Stack Web Development course is available both offline and online."},
    // {"key": "how long is the Flutter course?", "value": "The Flutter course lasts for 5 months with 2 hours of classes per day."},
    // {"key": "where is the Java Spring course held?", "value": "The Java Spring Full Stack Development course is held in Cochin only."},
    // {"key": "do you offer job placement?", "value": "We offer job placement assistance but do not guarantee job placement."},
    // {"key": "what is the duration of the Python Django course?", "value": "The Python Django Full Stack Web Development course is 6.5 months long."},
    // {"key": "can I attend the course in Calicut?", "value": "Yes, courses are available in Calicut. Check specific courses for availability."},
    // {"key": "how can I enroll in a course?", "value": "To enroll in a course, visit our website, select the course, and complete the registration form."},
    // {"key": "are course materials included?", "value": "Yes, all necessary course materials are included in the course fee."},
    // {"key": "is there an EMI option?", "value": "Yes, EMI options are available for most courses."},
    // {"key": "when does the MEAN stack course start?", "value": "The next MEAN Stack Web Development course starts on August 12th, 2024, in Cochin and July 19th, 2024, in Calicut."},
    // {"key": "what is covered in the API Testing course?", "value": "The API Testing course covers Postman, Swagger, and other API testing tools."},
    // {"key": "are there any prerequisites for the Java Spring course?", "value": "Basic knowledge of Java programming is recommended."},
    // {"key": "how do I contact support?", "value": "You can contact support by emailing support@example.com or through the help desk on our website."},
    // {"key": "can I get a trial class?", "value": "Yes, you can request a trial class to get an overview of the course."},
    // {"key": "what is the focus of the Automation Testing course?", "value": "The Automation Testing course focuses on tools like Selenium IDE, Selenium WebDriver, and TestNG for automating test processes."},
    // {"key": "is there a refund policy?", "value": "Yes, we have a refund policy. Please review the terms on our website or contact support for details."},
    // {"key": "where can I view course schedules?", "value": "Course schedules are available on the course pages of our website."},
    // {"key": "how do I update my profile?", "value": "You can update your profile by logging into your account on our website and editing your details."},
    // {"key": "can I access recordings of online classes?", "value": "Yes, recordings of online classes are available on the learning platform."},
    // {"key": "what is the duration of the manual testing course?", "value": "The Manual Testing course duration is 4 months, with classes held 5 days a week."},
    // {"key": "what tools are used in the JMeter course?", "value": "The JMeter course covers advanced topics in JMeter for performance testing."},
    // {"key": "is there a mobile app for courses?", "value": "Currently, we provide access to courses through our website. There is no dedicated mobile app."},
    // {"key": "how can I request a course extension?", "value": "To request a course extension, please contact our support team with your request and reason for extension."},
    // {"key": "can I get a certificate if I miss some classes?", "value": "Certificates are awarded upon completing all course requirements, including attendance, assignments, and projects."},
    // {"key": "what is covered in the React course?", "value": "The React course covers building user interfaces, state management, and component-based architecture."},
    // {"key": "is there a group study option?", "value": "Yes, group study options and collaborative projects are available in many of our courses."},
    // {"key": "when does the next batch for the Asp.net MVC course start?", "value": "The next batch for the Asp.net MVC course starts on July 17th, 2024."},
    // {"key": "how do I access course assignments?", "value": "Course assignments can be accessed and submitted through the learning platform."},
    // {"key": "are there any live sessions?", "value": "Yes, many courses include live sessions for real-time interaction with instructors."},
    // {"key": "how do I get a demo of the course?", "value": "You can request a demo class by contacting our support team."},
    // {"key": "what is the focus of the Python Data Science course?", "value": "The Python Data Science course focuses on data analysis, machine learning, and data visualization using Python."},
    // {"key": "how can I get a refund if I withdraw?", "value": "Refunds are subject to our refund policy. Please review the terms on our website or contact support for more information."}

]
